//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtTesla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modelo
    {
        public Modelo()
        {
            this.Veiculo = new HashSet<Veiculo>();
        }
    
        public int MODELID { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<System.DateTime> ANO { get; set; }
    
        public virtual ICollection<Veiculo> Veiculo { get; set; }
    }
}
