//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtTesla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public int VEID { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<int> VALOR { get; set; }
        public Nullable<int> MODELID { get; set; }
    
        public virtual Modelo Modelo { get; set; }
    }
}
