'------------------------------------------------------------------------------
' <auto-generated>
'    O código foi gerado a partir de um modelo.
'
'    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
'    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Professor
    Public Property PROFID As Integer
    Public Property PROFNOME As String
    Public Property TURID As Nullable(Of Integer)

    Public Overridable Property Turno As Turno

End Class
