'------------------------------------------------------------------------------
' <auto-generated>
'    O código foi gerado a partir de um modelo.
'
'    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
'    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Turno
    Public Property TURID As Integer
    Public Property TURDESCRICAO As String

    Public Overridable Property Professor As ICollection(Of Professor) = New HashSet(Of Professor)

End Class
